#!/usr/bin/env python3

import argparse

from loganalyzer.analyze import analyze


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-j", "--jobs", help="Number of jobs",
                        required=False, dest="jobs")
    parser.add_argument("-m", "--mode", help="Input analyzer mode",
                        required=False, dest="mode")
    parser.add_argument("-p", "--path", help="Input file path",
                        required=True, dest='path')
    parser.add_argument("-r", "--recursive", help="Make recursive analytics",
                        action="store_true", dest="recursive")
    parser.add_argument("-s",
                        "--save_path", help="Output saving path.", dest='save_path')
    parser.add_argument("-H", "--heatmap", help="Show Heatmap",
                        dest='heat_map')
    parser.add_argument("-V", '--version', action='version', version='1.0.0')
    args = parser.parse_args()
    if args.save_path is None:
        args.save_path = args.path+".log.json"
    return args


if __name__ == "__main__":
    analyze(parse_args())
